[package]
cairo-version = "=2.11.4"
name = "dojo_intro"
version = "1.7.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.11.4"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.11.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
