world_address = "0x025f8086d3f8ab846ee991d67763b4d321fbf92018fde5b2d424a07801dad227"
rpc="https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]


[grpc]
# Enable gRPC-web
port = 8080
addr = "0.0.0.0"

[relay]
# If using relay server
port = 9090
addr = "0.0.0.0"